<?php $title = 'Mes annonces';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('annonce', array('action'=>'add'));?>">Add new annonce</a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Description</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($annonces as $annonce) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($annonce->titre);?></td>
     <td><?php echo $this->escapeHtml($annonce->description);?></td>
     <td>
         <a href="<?php echo $this->url('annonce',
             array('action'=>'edit', 'id' => $annonce->id));?>">Edit</a>
         <a href="<?php echo $this->url('annonce',
             array('action'=>'delete', 'id' => $annonce->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>