<?php
$title = 'Edit utilisateur';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'utilisateur',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nom'));
 echo $this->formRow($form->get('prenom'));
 echo $this->formRow($form->get('mail'));
 echo $this->formRow($form->get('telephone'));
 echo $this->formRow($form->get('adresse'));
 echo $this->formRow($form->get('code_postal'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();