<?php $title = 'My utilisateurs';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('utilisateur', array('action'=>'add'));?>">Add new utilisateur</a>
 </p>

 <table class="table">
 <tr>
     <th>Nom</th>
     <th>Prénom</th>
     <th>Téléphone</th>
     <th>Mail</th>
     <th>Adresse</th>
     <th>Code Postal</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($utilisateurs as $utilisateur) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($utilisateur->title);?></td>
     <td><?php echo $this->escapeHtml($utilisateur->artist);?></td>
     <td><?php echo $this->escapeHtml($utilisateur->nom);?></td>
     <td><?php echo $this->escapeHtml($utilisateur->prenom);?></td>
     <td>
         <a href="<?php echo $this->url('utilisateur',
             array('action'=>'edit', 'id' => $utilisateur->id));?>">Edit</a>
         <a href="<?php echo $this->url('utilisateur',
             array('action'=>'delete', 'id' => $utilisateur->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>